# Generated by Django 3.2.11 on 2022-01-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=32, verbose_name='书本名称')),
                ('unit', models.SmallIntegerField(verbose_name='单元')),
                ('classes', models.SmallIntegerField(verbose_name='课次')),
                ('word', models.CharField(max_length=32, verbose_name='外语单词')),
                ('symbol', models.CharField(max_length=64, verbose_name='音标')),
                ('voice', models.CharField(max_length=32, verbose_name='读音')),
                ('cn', models.CharField(max_length=64, verbose_name='中文释义')),
                ('word_type', models.CharField(max_length=16, verbose_name='词性')),
                ('sentence', models.CharField(max_length=512, verbose_name='例句')),
            ],
        ),
    ]
