# Generated by Django 3.2.11 on 2022-01-21 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=32, verbose_name='书本名称')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, verbose_name='外语单词')),
                ('symbol', models.CharField(max_length=64, verbose_name='音标')),
                ('voice', models.CharField(max_length=64, verbose_name='读音')),
                ('cn', models.CharField(max_length=64, verbose_name='中文释义')),
                ('word_type', models.CharField(max_length=32, verbose_name='词性')),
                ('sentence', models.CharField(max_length=512, verbose_name='例句')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.lesson', verbose_name='课次')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('name', models.CharField(max_length=32, verbose_name='单元名称')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.book', verbose_name='书本')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.unit', verbose_name='单元'),
        ),
    ]
