# Generated by Django 3.2.11 on 2022-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_auto_20220121_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='课次名称'),
            preserve_default=False,
        ),
    ]
