# Generated by Django 3.2.11 on 2022-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0003_lesson_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words',
        ),
        migrations.AlterField(
            model_name='word',
            name='symbol',
            field=models.FileField(upload_to='media/upload', verbose_name='音标'),
        ),
    ]
