# Generated by Django 3.2.11 on 2022-01-24 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('book', models.CharField(max_length=8, verbose_name='单词书')),
                ('unit', models.CharField(max_length=8, verbose_name='单元')),
                ('lesson', models.CharField(max_length=8, verbose_name='课次')),
                ('amount', models.IntegerField(default=20, verbose_name='题目数量')),
                ('max_total_time', models.IntegerField(default=7200, verbose_name='最大总答题时间（秒）')),
                ('max_word_time', models.IntegerField(default=120, verbose_name='单词最大答题时间（秒）')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对题数')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='测试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='用户')),
            ],
        ),
    ]
