# Generated by Django 3.2.11 on 2022-01-24 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20220121_1600'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.book', verbose_name='单词书'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.lesson', verbose_name='课次'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.unit', verbose_name='单元'),
        ),
    ]
