# Generated by Django 3.2.11 on 2022-01-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220124_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='题目数量'),
        ),
    ]
