# Generated by Django 3.2.11 on 2022-01-25 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0005_auto_20220121_1600'),
        ('account', '0001_initial'),
        ('quiz', '0004_alter_quiz_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='完成时间')),
                ('amount', models.IntegerField(verbose_name='题目总数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='答对题数')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='测试')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='quizLogErr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.CharField(max_length=64, verbose_name='错误记录')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz', verbose_name='测试')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word', verbose_name='单词')),
            ],
        ),
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
