# Generated by Django 3.2.11 on 2022-01-19 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=32, null=True, verbose_name='描述')),
                ('type', models.SmallIntegerField(choices=[(1, '书名'), (2, '单元'), (1, '课次')], verbose_name='类型')),
                ('c_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='management.classify', verbose_name='关联的上级分类')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, verbose_name='外语单词')),
                ('symbol', models.CharField(max_length=64, verbose_name='音标')),
                ('voice', models.CharField(max_length=32, verbose_name='读音')),
                ('cn', models.CharField(max_length=64, verbose_name='中文释义')),
                ('word_type', models.CharField(max_length=16, verbose_name='词性')),
                ('sentence', models.CharField(max_length=512, verbose_name='例句')),
            ],
        ),
        migrations.CreateModel(
            name='WordClassify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.classify', verbose_name='分类')),
                ('w_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.wordclassify', verbose_name='单词')),
            ],
        ),
    ]
